In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [16]:
li=pd.Series([1,2,3],index=['a','b','c'])
list(li.index)

['a', 'b', 'c']

In [30]:
dates=pd.date_range('2014-07-01', '2014-07-06')
z=pd.Series(range(len(dates)),index=dates)
temps2 = pd.Series([70, 75, 69, 83, 79, 77],index = dates)
print(f'Z:\n{z } \n\n temp2:\n{temps2}\n \n this is divided:\n {temps2 - z}')


Z:
2014-07-01    0
2014-07-02    1
2014-07-03    2
2014-07-04    3
2014-07-05    4
2014-07-06    5
Freq: D, dtype: int64 

 temp2:
2014-07-01    70
2014-07-02    75
2014-07-03    69
2014-07-04    83
2014-07-05    79
2014-07-06    77
Freq: D, dtype: int64
 
 this is divided:
 2014-07-01    70
2014-07-02    74
2014-07-03    67
2014-07-04    80
2014-07-05    75
2014-07-06    72
Freq: D, dtype: int64


In [80]:
zz=pd.Series([1,2,3],index=pd.date_range('2014-07-01', '2014-07-03'))
temps_df = pd.DataFrame({'Missoula': z,
                'Philadelphia': temps2})
# tem_df=pd.DataFrame(zz,columns=['one'],index=zz.index)

temps_df['Difference']=temps_df.Missoula - temps_df['Philadelphia']
temps_df

Missoula  Philadelphia  Difference
2014-07-01         0            70         -70
2014-07-02         1            75         -74
2014-07-03         2            69         -67
2014-07-04         3            83         -80
2014-07-05         4            79         -75
2014-07-06         5            77         -72

In [100]:
#the same 
# temps_df.iloc[[1, 3, 5]]['Difference']
# temps_df.iloc[[1, 3, 5]].Difference 
temps_df[temps_df.Difference < -70] 

Missoula  Philadelphia  Difference
2014-07-02         1            75         -74
2014-07-04         3            83         -80
2014-07-05         4            79         -75
2014-07-06         5            77         -72

In [ ]:
df = pd.read_csv('data/test1.csv', parse_dates=['date'],index_col='some')

In [108]:
na=np.array(np.arange(2.5,10,2))


array([2.5, 4.5, 6.5, 8.5])

In [147]:
na[2:], na.size # size of array
# print(len(na))
# In numpy array we have size and the len
np.arange(0, 10+1, 2)
np.arange(10,0,-1) # Counting Down
print(np.linspace(1, 10,4))
print(np.arange(0,10,2))

nz=np.array([[1,2,3],[1,4,5]])
nz

[ 1.  4.  7. 10.]
[0 2 4 6 8]


array([[1, 2, 3],
       [1, 4, 5]])

In [182]:
nz[0,0:3] # Slicing
nz.size
# len(nz)
nz[:,2]
a = np.arange(5)
# a[a< 2]
np.sum(a < 3) # sum of the element less than 3
a1 = np.arange(1, 10)
a1[3:8] ,a1
a1[::3],a1
a1[9:0:-1],a1 #reversed


(array([9, 8, 7, 6, 5, 4, 3, 2]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [187]:
a = np.arange(0, 9)
# and reshape to a 3x3 2-d array
m = a.reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [196]:
m_reval=m.ravel() # Generate the Flatt 2-D array
m_reval.size, len (m_reval)

(9, 9)

In [229]:

zp=np.array([[1,2,3],[4,1,4],[21,4,7],[1,5,8]])
# zp.size, 
zp, zp.transpose(), zp.T ==zp.transpose()

(array([[ 1,  2,  3],
        [ 4,  1,  4],
        [21,  4,  7],
        [ 1,  5,  8]]),
 array([[ 1,  4, 21,  1],
        [ 2,  1,  4,  5],
        [ 3,  4,  7,  8]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

In [239]:
a = np.arange(9).reshape(3, 3)
b= a*10

np.hstack((a,b)), np.concatenate((a, b), axis = 1)


(array([[ 0,  1,  2,  0, 10, 20],
        [ 3,  4,  5, 30, 40, 50],
        [ 6,  7,  8, 60, 70, 80]]),
 array([[ 0,  1,  2,  0, 10, 20],
        [ 3,  4,  5, 30, 40, 50],
        [ 6,  7,  8, 60, 70, 80]]))

In [263]:
print('a:\n {} \n \n b:\n {} '.format( a ,b))
# np.dstack((a, b))
np.column_stack((np.ravel(a),np.ravel(b)))

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 
 b:
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]] 


array([[ 0,  0],
       [ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60],
       [ 7, 70],
       [ 8, 80]])

In [295]:
a = np.arange(12).reshape(4, 3)
print(a)

# np.split(a, 3, axis = 1)
np.hsplit(a, 3) ,np.vsplit(a, 4)
np.split(a, 2, axis = 0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [307]:
m = np.arange(10, 19).reshape(3, 3)
print(m)
m.argmax(),m.max(), m.min(axis = 1), m.max(axis = 0) # 0 mean columns and 1 is row
m.cumsum(), m.cumprod()
m.ravel().ndim

[[10 11 12]
 [13 14 15]
 [16 17 18]]


1

### creting Seires and Dataframe


In [345]:
s3=pd.Series([2])
np.random.seed(123456)
s8=pd.Series(np.random.randn(5),index=pd.date_range('2022-01-01','2022-01-5'))
s6 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4}) # from dict
s6

a    1
b    2
c    3
d    4
dtype: int64

In [347]:
s7=pd.Series([[1,2,3,np.nan],[5,1,7,np.nan],np.nan])
s8, s7

(2022-01-01    0.469112
 2022-01-02   -0.282863
 2022-01-03   -1.509059
 2022-01-04   -1.135632
 2022-01-05    1.212112
 Freq: D, dtype: float64,
 0    [1, 2, 3, nan]
 1    [5, 1, 7, nan]
 2               NaN
 dtype: object)

In [377]:
# s7.value_counts(), s8.value_counts()
s8.take([0, 4]),'\n', s8[[0,4]]
s8.loc['2022-01-01'], s8.iloc[4]
# s8.iloc[[1,2]]
# s8.ix['2022-01-01','2022-01-02']
# s8[0]

(0.4691122999071863, 1.2121120250208506)

In [386]:
s6 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s9=pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s8 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})

print(s6.values + s9.values) # Via values of each clumns
s6 +s9  # Via index (the order is not important)
s8+ s9 # via index (the missing pair of index return the NaN)

[5 5 5 5]


a     NaN
b     8.0
c    10.0
d    13.0
e     NaN
dtype: float64

In [417]:
nda = np.array([1, 2, 3, 4, np.NaN,30,40,100])
nda.mean(),nda.std()
s = pd.Series(nda)
s.mean()
s.mean(skipna=False)
s=s+20

In [465]:
# print(s)
# s[(s > 20) & (s <= 50)]
s[(s <40) | (s >20)] # AND
(s >= 0).all()
(s <= 24).sum()

s1 = pd.Series(np.random.randn(3),index=['a','2','c'])
s2 = pd.Series(np.random.randn(3),index=s1.index)
combined = pd.concat([s1, s2],axis=1)
combined.columns=['a','b']
combined.index=[np.arange(len(combined))]

# combined
print(f' combined: \n {combined}')
s1,s2, 


 combined: 
           a         b
0  0.408204 -0.988387
1 -1.048089  0.094055
2 -0.025747  1.262731


(a    0.408204
 2   -1.048089
 c   -0.025747
 dtype: float64,
 a   -0.988387
 2    0.094055
 c    1.262731
 dtype: float64)

In [479]:
s3=s2.reindex(['b','g','a'])
s3


b         NaN
g         NaN
a   -0.489682
dtype: float64

In [481]:
s1 = pd.Series(np.random.randn(4), [1, 'b', 'c', 'd'])
s2 = s1.reindex(['a', 'c', 'g'])
s1,s2

(1   -0.977349
 b    1.474071
 c   -0.064034
 d   -1.282782
 dtype: float64,
 a         NaN
 c   -0.064034
 g         NaN
 dtype: float64)

In [500]:
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])
s2 = pd.Series([3, 4, 5], index=['0', '1', '2'])
s2.index = s2.index.values.astype(int)
s2 + s1 


0    3
1    5
2    7
dtype: int64

In [527]:

s4=pd.Series(np.arange(5))
s4.index=['f','b','c','e','a']
print(s4)
s4.reindex(['a', 'f','cc'],fill_value=0)

f    0
b    1
c    2
e    3
a    4
dtype: int32


a     4
f     0
cc    0
dtype: int32

In [529]:
s = pd.Series(np.arange(100, 110), index=np.arange(10, 20))
s

10    100
11    101
12    102
13    103
14    104
15    105
16    106
17    107
18    108
19    109
dtype: int32

In [534]:
s.iloc[[1,2]]
s[:5:2]
s[4: :2] # start at fourth pos stepping 2

C:\Users\erfan\AppData\Local\Temp\ipykernel_14152\3396612188.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  s[:5:2]
C:\Users\erfan\AppData\Local\Temp\ipykernel_14152\3396612188.py:3: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  s[4: :2]


14    104
16    106
18    108
dtype: int32